version: "3"
services:
  user_service_db:
    image: 'postgres:14.2-bullseye'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=label_bkict_user_service_db
    restart: always
    volumes:
      - ../db-data/user_service:/var/lib/postgresql/data
  image_service_db:
    image: 'postgres:14.2-bullseye'
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=label_bkict_image_service_db
    restart: always
    volumes:
      - ../db-data/image_service:/var/lib/postgresql/data
  export_service_db:
    image: 'postgres:14.2-bullseye'
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=label_bkict_export_service_db
    restart: always
    volumes:
      - ../db-data/export_service:/var/lib/postgresql/data
  model_service_db:
    image: 'postgres:14.2-bullseye'
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=label_bkict_model_service_db
    restart: always
    volumes:
      - ../db-data/model_service:/var/lib/postgresql/data
  pin_page_service_db:
    image: 'postgres:14.2-bullseye'
    ports:
      - '5436:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=label_bkict_pin_page_service_db
    restart: always
    volumes:
      - ../db-data/pin_page_service:/var/lib/postgresql/data
  zookeeper:
    image: 'bitnami/zookeeper:3.8-debian-10'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always
  kafka:
    image: 'bitnami/kafka:3.1-debian-10'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    restart: always

  elk:
    image: sebp/elk:8.3.3
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - MAX_MAP_COUNT=262144
    volumes:
      - ../elk-data:/var/lib/elasticsearch
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address "0.0.0.0:9001"
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    restart: always
    volumes:
      - ../minio-data:/data 